In [310]:
import pandas as pd;
import numpy as np;

In [312]:
df= pd.read_csv('online_retail.csv')

In [313]:
df

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,currency_map,Revenue,Transaction_Type
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,£,15.30,Sales
1,1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,£,20.34,Sales
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,£,22.00,Sales
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,£,20.34,Sales
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,£,20.34,Sales
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,€,10.20,Sales
541905,541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,€,12.60,Sales
541906,541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,€,16.60,Sales
541907,541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,€,16.60,Sales
541908,541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,€,14.85,Sales

In [314]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             541909 non-null  int64
 1   InvoiceNo         541909 non-null  object
 2   StockCode         541909 non-null  object
 3   Description       540455 non-null  object
 4   Quantity          541909 non-null  int64
 5   InvoiceDate       541909 non-null  object
 6   UnitPrice         541909 non-null  float64
 7   CustomerID        406829 non-null  float64
 8   Country           541909 non-null  object
 9   currency_map      541463 non-null  object
 10  Revenue           541909 non-null  float64
 11  Transaction_Type  541909 non-null  object
dtypes: float64(3), int64(2), object(7)
memory usage: 49.6+ MB

In [315]:
df.describe()

,index,Quantity,UnitPrice,CustomerID,Revenue
count,541909.00000,541909.000000,541909.000000,406829.000000,541909.000000
mean,270954.00000,9.552250,4.611114,15287.690570,17.987795
std,156435.79785,218.081158,96.759853,1713.600303,378.810824
min,0.00000,-80995.000000,-11062.060000,12346.000000,-168469.600000
25%,135477.00000,1.000000,1.250000,13953.000000,3.400000
50%,270954.00000,3.000000,2.080000,15152.000000,9.750000
75%,406431.00000,10.000000,4.130000,16791.000000,17.400000
max,541908.00000,80995.000000,38970.000000,18287.000000,168469.600000

In [316]:
df.head(5)

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,currency_map,Revenue,Transaction_Type
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,£,15.30,Sales
1,1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,£,20.34,Sales
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,£,22.00,Sales
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,£,20.34,Sales
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,£,20.34,Sales

df.drop_duplicates().count()

Checking Duplicates

In [319]:
df[df.duplicated()]

Empty DataFrame
Columns: [index, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, currency_map, Revenue, Transaction_Type]
Index: []

In [326]:
df[df.isnull()].count()

index               0
InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID          0
Country             0
currency_map        0
Revenue             0
Transaction_Type    0
dtype: int64

In [327]:
df['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [330]:
currency_map = {
    "United Kingdom": "£",
    "France": "€",
    "Australia": "$",
    "Netherlands": "€",
    "Germany": "€",
    "Norway": "kr",
    "EIRE": "€",
    "Switzerland": "CHF",
    "Spain": "€",
    "Poland": "zł",
    "Portugal": "€",
    "Italy": "€",
    "Belgium": "€",
    "Lithuania": "€",
    "Japan": "¥",
    "Iceland": "kr",
    "Channel Islands": "£",
    "Denmark": "kr",
    "Cyprus": "€",
    "Sweden": "kr",
    "Austria": "€",
    "Israel": "₪",
    "Finland": "€",
    "Bahrain": "BD",
    "Greece": "€",
    "Hong Kong": "HK$",
    "Singapore": "S$",
    "Lebanon": "ل.ل",
    "United Arab Emirates": "د.إ",
    "Saudi Arabia": "﷼",
    "Czech Republic": "Kč",
    "Canada": "$",
    "Unspecified": None,
    "Brazil": "R$",
    "USA": "$",
    "European Community": "€",
    "Malta": "€",
    "RSA": "R"
}

In [332]:
df['currency_map']=df['Country'].map(currency_map)

Transaction Type,
Calculating Revenue

In [335]:
df['Transaction_Type']= df['Quantity'].apply(lambda x : 'Sales' if x >0 else 'Returns')

In [337]:
df['Revenue']= df['Quantity']* df['UnitPrice']

Gross Revenue → Only positive sales

Return Amount → Absolute value of negative revenue

Net Revenue → Gross Revenue – Returns

Return Rate (%) → Returns / Gross Revenue

In [340]:
gross_revenue = df[df['Quantity'] > 0]['Revenue'].sum()

In [342]:
gross_revenue

10644560.424

In [344]:
refund_amount= abs(df[df['Quantity'] < 0] ['Revenue'].sum())

In [346]:
refund_amount

896812.49

In [348]:
Net_Revenue= gross_revenue-refund_amount

In [350]:
Net_Revenue

9747747.934

In [352]:
Refund_Rate= f'{(refund_amount/gross_revenue)*100:.2f}%'

In [354]:
Refund_Rate

'8.43%'

In [356]:
df.to_csv('online_retail.csv', index=False)

In [357]:
from sqlalchemy import create_engine

In [358]:
username = "root2" 
password = "Mikey%409110311694" 
host = "localhost"
port = 3306 
database = "OnlineRetail" 
engine = create_engine( f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}" )

In [359]:
try:
    with engine.connect() as conn:
        print("Connection successful — password is correct")
except Exception as e:
    print("Connection failed — password may be wrong or MySQL is not running")
    print("Error:", e)

Connection successful — password is correct

In [366]:
df.to_sql("online_retail_table", engine, if_exists="replace", index=False)

541909